"""empty message

Revision ID: 6eaa76b4d359
Revises: e622b82dc5b4
Create Date: 2022-05-14 08:42:19.051333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6eaa76b4d359'
down_revision = 'e622b82dc5b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('packageinfo_table', sa.Column('HPkgSlipName', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('packageinfo_table', 'HPkgSlipName')
    # ### end Alembic commands ###
