"""empty message

Revision ID: e622b82dc5b4
Revises: ec39e4c2bb13
Create Date: 2022-05-13 13:59:32.011108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e622b82dc5b4'
down_revision = 'ec39e4c2bb13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('packageinfo_table', sa.Column('HPkgBalAmtReceived', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('packageinfo_table', 'HPkgBalAmtReceived')
    # ### end Alembic commands ###
